In [1]:
# Import all libraries needed for the tutorial
# General syntax to import specific functions in a library: 
##from (library) import (specific library function)
from pandas import DataFrame, read_csv
# General syntax to import a library but no functions: 
##import (library) as (give the library a nickname/alias)
import matplotlib.pyplot as plt
import pandas as pd #this is how I usually import pandas
import sys #only needed to determine Python version number
import matplotlib #only needed to determine Matplotlib version number
import functools
from spectrum import *
from pylab import plot
from scipy import signal
import numpy as np
import time
from scipy import stats

In [3]:
print('Python version ' + sys.version)
print('Pandas version ' + pd.__version__)
print('Matplotlib version ' + matplotlib.__version__)

Python version 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
Pandas version 0.23.0
Matplotlib version 2.2.2

In [4]:
from datetime import timedelta, date
def daterange(start_date, end_date):
    for n in range(int ((end_date - start_date).days)):
        yield start_date + timedelta(n)

start_date = date(2018, 8, 7)
end_date = date(2018, 8, 29)

In [12]:
Location1 =  str('C:/Users/euripab/Desktop/ML Extraction/20180421_20180427_ALL_INTACTE.CSV')
data_2 = pd.read_csv(Location1, sep=';', encoding='latin-1')
data_2 = data_2.replace(r'\N',np.nan)
data_2['DAY'] = pd.to_datetime(data_2['DAY'],infer_datetime_format=True)
data_2 = data_2.set_index('DAY')
data_2 = data_2.between_time('7:00','23:00')

C:\Users\euripab\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (33,35,66,123,280,282,287,431,439,440,447,463,476,484,502,527,530,531,532,930,931,933,934,939,944,964,970,975,994) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [13]:
date_data

,DAY,Constructeur,Région,Département,Site Théorique,eNodeBName,Secteur,CellName,Info Supplémentaire,Utilisation Moy.PRB - PUSCH Load,...,% PDCP Packet Loss rate UL QCi3,% PDCP Packet Loss rate UL QCi4,% PDCP Packet Loss rate UL QCi5,% PDCP Packet Loss rate UL QCi6,% PDCP Packet Loss rate UL QCi7,% PDCP Packet Loss rate UL QCi8,% PDCP Packet Loss rate UL QCi9,% BYTEL.Répartition de Trafic UL,% de Reestab par appel,Unnamed: 1004
0,21/04/2018 00:00:00,EUTRAN,P,75,T16733,E16733,A16733A,T16733A,NaN,"5,69",...,NaN,NaN,0,0,"0,06","0,07","1,32",100.0,"15,71",NaN
1,21/04/2018 00:00:00,EUTRAN,P,75,T16733,E16733,A16733B,T16733B,NaN,"7,59",...,NaN,NaN,"0,01","0,01","0,35","0,14","0,94",100.0,"17,65",NaN
2,21/04/2018 00:00:00,EUTRAN,P,75,T16733,E16733,A16733C,T16733C,NaN,"7,03",...,NaN,NaN,0,"0,02","0,09","0,12",0,100.0,6,NaN
3,21/04/2018 00:00:00,EUTRAN,P,75,T18033,E98011,A18033A,T16759A,NaN,"6,54",...,NaN,NaN,0,0,"0,06","0,38","0,01",100.0,"9,80",NaN
4,21/04/2018 00:00:00,EUTRAN,P,75,T18033,E98011,A18033B,T16759B,NaN,"7,95",...,NaN,NaN,"1,07","0,01","0,09","0,05","0,10",100.0,"8,93",NaN
5,21/04/2018 00:00:00,EUTRAN,P,75,T18033,E98011,A18033C,T16759C,NaN,"10,64",...,NaN,NaN,0,0,"0,09","0,04","0,01",100.0,"4,26",NaN
6,21/04/2018 00:00:00,EUTRAN,P,75,T16785,E03474,A16785A,T16785A,NaN,"5,19",...,NaN,NaN,0,0,"0,04",0,0,100.0,"12,50",NaN
7,21/04/2018 00:00:00,EUTRAN,P,75,T16785,E03474,A16785B,T16785B,NaN,"5,01",...,NaN,NaN,0,0,"0,15",0,0,100.0,"15,79",NaN
8,21/04/2018 00:00:00,EUTRAN,P,75,T16785,E03474,A16785C,T16785C,NaN,5,...,NaN,NaN,0,"0,03","0,31",0,0,100.0,0,NaN
9,21/04/2018 00:00:00,EUTRAN,P,75,T16798,E16798,A16798A,T16798A,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,21/04/2018 00:00:00,EUTRAN,P,75,T16798,E16798,A16798B,T16798B,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,21/04/2018 00:00:00,EUTRAN,P,75,T16798,E16798,A16798C,T16798C,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,21/04/2018 00:00:00,EUTRAN,P,92,T16876,E16876,A16876A,T16876A,NaN,"12,82",...,NaN,NaN,"0,20","0,03","0,06","0,32","2,44",100.0,"12,30",NaN
13,21/04/2018 00:00:00,EUTRAN,P,92,T16876,E16876,A16876B,T16876B,NaN,"5,55",...,NaN,NaN,0,"0,02","0,18","0,36","0,35",100.0,"37,50",NaN
14,21/04/2018 00:00:00,EUTRAN,P,92,T16876,E16876,A16876C,T16876C,NaN,"10,84",...,NaN,NaN,0,0,"0,10","0,01","0,46",100.0,"10,87",NaN
15,21/04/2018 00:00:00,EUTRAN,P,92,T17003,E17003,A17003A,T17003A,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,21/04/2018 00:00:00,EUTRAN,P,92,T17003,E17003,A17003B,T17003B,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,21/04/2018 00:00:00,EUTRAN,P,75,T17080,E17080,A17080A,T17080A,NaN,"5,01",...,NaN,NaN,0,"0,03","0,03",0,"0,45",100.0,"66,67",NaN
18,21/04/2018 00:00:00,EUTRAN,P,92,T17172,E17172,A17172A,T17172A,NaN,"5,01",...,NaN,NaN,0,"0,55","0,47","0,53","4,47",100.0,200,NaN
19,21/04/2018 00:00:00,EUTRAN,P,92,T17172,E17172,A17172B,T17172B,NaN,"5,03",...,NaN,NaN,0,0,"0,29",0,0,100.0,"83,33",NaN
20,21/04/2018 00:00:00,EUTRAN,P,92,T17172,E17172,A17172C,T17172C,NaN,5,...,NaN,NaN,0,0,"0,50","0,01",0,100.0,"12,50",NaN
21,21/04/2018 00:00:00,EUTRAN,P,75,T17502,E17502,A17502A,T17502A,NaN,"5,01",...,NaN,NaN,"0,47",0,"3,07",0,0,100.0,"111,11",NaN
22,21/04/2018 00:00:00,EUTRAN,P,75,T17502,E17502,A17502B,T17502B,NaN,"5,01",...,NaN,NaN,0,"0,13","1,38","0,37","0,35",100.0,"33,33",NaN
23,21/04/2018 00:00:00,EUTRAN,P,75,T17512,E17512,A17512A,T17512A,NaN,"10,19",...,NaN,NaN,"0,19","0,55","0,93","1,07","0,56",100.0,"16,85",NaN
24,21/04/2018 00:00:00,EUTRAN,P,75,T17512,E17512,A17512B,T17512B,NaN,"7,38",...,NaN,NaN,"0,24","0,26","0,57","2,29","2,65",100.0,"39,25",NaN
25,21/04/2018 00:00:00,EUTRAN,P,75,T17512,E17512,A17512C,T17512C,NaN,"6,31",...,NaN,NaN,"0,30","0,06","0,76","0,97","1,76",100.0,"33,93",NaN
26,21/04/2018 00:00:00,EUTRAN,P,75,T17513,E04553,A17513A,T17513A,NaN,"5,34",...,NaN,NaN,"0,38","0,86","0,32",0,"0,01",100.0,"15,63",NaN
27,21/04/2018 00:00:00,EUTRAN,P,75,T17513,E04553,A17513B,T17513B,NaN,"5,21",...,NaN,NaN,0,"0,58","0,43",0,0,100.0,"12,50",NaN
28,21/04/2018 00:00:00,EUTRAN,P,75,T17513,E04553,A17513C,T17513C,NaN,"5,06",...,NaN,NaN,"0,05","0,01","0,50","1,75","0,45",100.0,"9,09",NaN
29,21/04/2018 00:00:00,EUTRAN,P,92,T17515,E02331,A17515A,T17515A,NaN,"5,24",...,NaN,NaN,0,0,"0,12",0,0,100.0,"15,38",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4387,27/04/2018 00:00:00,EUTRAN,P,75,T10697,E10697,A10697A,D10697A,NaN,"8,67",...,NaN,NaN,0,0,"0,02",0,0,100.0,"0,43",NaN
4388,27/04/2018 00:00:00,EUTRAN,P,75,T10697,E10697,A10697B,D10697B,NaN,"8,10",...,NaN,NaN,0,0,"0,04",0,0,100.0,"0,59",NaN
4389,27/04/2018 00:00:00,EUTRAN,P,75,T10697,E10697,A10697C,D10697C,NaN,"10,90",...,NaN,NaN,0,0,"0,04","0,03","0,01",100.0,"3,05",NaN
4390,27/04/2018 00:00:00,EUTRAN,P,75,T10939,E10939,A10939A,D10939A,NaN,"5,47",...,NaN,NaN,0,0,"0,01",0,0,100.0,"0,69",NaN
4391,27/04/2018 00:00:00,EUTRAN,P,75,T10939,E10939,A10939B,D10939B,NaN,"6,74",...,NaN,NaN,0,0,"0,02",0,0,100.0,0,NaN
4392,27/04/2018 00:00:00,EUTRAN,P,75,T10939,E10939,A10939C,D10939C,NaN,"5,32",...,NaN,NaN,0,"0,05","0,02","0,04",0,100.0,"7,39",NaN
4393,27/04/2018 00:00:00,EUTRAN,P,75,T10972,E10972,A10972A,D10972A,NaN,"8,28",...,NaN,NaN,"0,06",0,"0,02","0,01",0,100.0,"1,15",NaN
4394,27/04/2018 00:00:00,EUTRAN,P,75,T10972,E10972,A10972B,D10972B,NaN,"10,02",...,NaN,NaN,0,0,"0,05",0,"0,05",100.0,"1,04",NaN
4395,27/04/2018 00:00:00,EUTRAN,P,75,T10972,E10972,A10972C,D10972C,NaN,"15,88",...,NaN,NaN,0,"0,01","0,09","0,01","0,54",100.0,"2,60",NaN
4396,27/04/2018 00:00:00,EUTRAN,P,75,T10974,E10974,A10974A,D10974A,NaN,"18,28",...,NaN,NaN,0,"0,01","0,02","0,03","0,07",100.0,"2,21",NaN
4397,27/04/2018 00:00:00,EUTRAN,P,75,T11183,E11183,A11183A,D11183A,NaN,"5,08",...,NaN,NaN,0,0,"0,01",0,0,100.0,0,NaN
4398,27/04/2018 00:00:00,EUTRAN,P,75,T11183,E11183,A11183B,D11183B,NaN,"7,82",...,NaN,NaN,0,0,"0,02",0,"0,01",100.0,"2,75",NaN
4399,27/04/2018 00:00:00,EUTRAN,P,75,T11183,E11183,A11183C,D11183C,NaN,"5,04",...,NaN,NaN,0,"0,04",0,0,0,100.0,0,NaN
4400,27/04/2018 00:00:00,EUTRAN,P,75,T11648,E11648,A11648A,D11648A,NaN,"5,02",...,NaN,NaN,0,0,0,0,0,100.0,0,NaN
4401,27/04/2018 00:00:00,EUTRAN,P,75,T11648,E11648,A11648B,D11648B,NaN,"5,57",...,NaN,NaN,0,0,0,0,NaN,100.0,0,NaN
4402,27/04/2018 00:00:00,EUTRAN,P,75,T11648,E11648,A11648C,D11648C,NaN,"5,01",...,NaN,NaN,0,0,0,0,NaN,100.0,0,NaN
4403,27/04/2018 00:00:00,EUTRAN,P,92,T11836,E11836,A11836A,D11836A,NaN,"5,84",...,NaN,NaN,"0,01",0,"0,06",0,0,100.0,"2,92",NaN
4404,27/04/2018 00:00:00,EUTRAN,P,92,T11836,E11836,A11836B,D11836B,NaN,"17,57",...,NaN,NaN,0,0,"0,06","0,09",0,100.0,"3,42",NaN
4405,27/04/2018 00:00:00,EUTRAN,P,92,T11837,E11837,A11837A,D11837A,NaN,"5,69",...,NaN,NaN,0,0,"0,01",0,0,100.0,"0,37",NaN
4406,27/04/2018 00:00:00,EUTRAN,P,92,T11837,E11837,A11837B,D11837B,NaN,"16,10",...,NaN,NaN,0,0,0,0,0,100.0,"0,60",NaN
4407,27/04/2018 00:00:00,EUTRAN,P,92,T11837,E11837,A11837C,D11837C,NaN,"5,08",...,NaN,NaN,0,0,"0,04",0,0,100.0,0,NaN
4408,27/04/2018 00:00:00,EUTRAN,P,75,T12455,E12455,A12455A,D12455A,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4409,27/04/2018 00:00:00,EUTRAN,P,75,T12463,E12463,A12463A,D12463A,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4410,27/04/2018 00:00:00,EUTRAN,P,75,T12487,E12487,A12487A,D12487A,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4411,27/04/2018 00:00:00,EUTRAN,P,75,T18033,E98009,A18033A,D13307A,NaN,"5,50",...,NaN,NaN,0,0,0,0,"0,39",100.0,"2,33",NaN
4412,27/04/2018 00:00:00,EUTRAN,P,75,T13319,E13319,A13319A,D13319A,NaN,"6,48",...,NaN,NaN,0,0,"0,01","0,02",0,100.0,"1,15",NaN
4413,27/04/2018 00:00:00,EUTRAN,P,75,T14431,E14431,A14431A,D14431A,NaN,"5,05",...,NaN,NaN,0,0,0,"0,25",0,100.0,"4,17",NaN
4414,27/04/2018 00:00:00,EUTRAN,P,75,T14837,E14837,A14837A,D14837A,NaN,"5,16",...,NaN,NaN,0,"0,02","0,08",0,0,100.0,"4,26",NaN
4415,27/04/2018 00:00:00,EUTRAN,P,75,T14837,E14837,A14837B,D14837B,NaN,"5,16",...,NaN,NaN,0,0,"0,02",0,0,100.0,0,NaN
4416,27/04/2018 00:00:00,EUTRAN,P,75,T14837,E14837,A14837C,D14837C,NaN,5,...,NaN,NaN,"0,48",0,"0,31",0,0,100.0,0,NaN

In [9]:
#Clean Cells That Have only 0 values for 
def CleanNullCells(ZoneDataFrame):
    for kpi in ZoneDataFrame.columns:
        for cell in ZoneDataFrame['CellName'].unique():
            CelluleData = ZoneDataFrame.loc[ZoneDataFrame['CellName']==cell][['DAY_',kpi]]
            if(CelluleData[kpi] == 0).all():
                  ZoneDataFrame = ZoneDataFrame.loc[ZoneDataFrame['CellName'] != cell]
    return(ZoneDataFrame)

In [14]:
def nanPorcentageOfKpis(kpisDataFrame):
    NaNDataFrame = pd.DataFrame()
    for kpi in kpisDataFrame.columns:
        count_nan = len(kpisDataFrame[kpi]) - kpisDataFrame[kpi].count()
        NaNDataFrame.loc[kpi,'NaN%'] = count_nan/len(kpisDataFrame[kpi])
    return(NaNDataFrame)

In [17]:
NaNAnalyse = nanPorcentageOfKpis(data_2)

C:\Users\euripab\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in long_scalars
  """

In [19]:
local_path = 'C:/Users/euripab/Desktop/ML Extraction/'
fic_result= local_path + "NaNQuotidienneKpiAnalyse.csv"
NaNAnalyse.to_csv(fic_result)